hmrc/corporation-tax-frontend

app/connectors/CtConnector.scala
app/connectors/models/CtAccountSummaryData.scala
app/models/CtAccountSummary.scala
app/models/CtEnrolment.scala
app/services/CtService.scala
project/FrontendBuild.scala
test/connectors/CtConnectorSpec.scala
test/services/CtServiceSpec.scala

* Added the CtService file and all the models that are needed
* Added an extra test to check inactivated enrolment

BTA-350 | added ct service

---

app/assets/stylesheets/partials/_forms.scss
app/config/FrontendAppConfig.scala
app/controllers/StopController.scala
app/controllers/actions/ServiceInfoAction.scala
app/forms/StopFormProvider.scala
app/identifiers/StopId.scala
app/models/Stop.scala
app/utils/Navigator.scala
app/utils/NextPage.scala
app/views/components/input_radio.scala.html
app/views/components/language_selection.scala.html
app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html
app/views/stop.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
conf/messages.en
migrations/applied_migrations/Stop.sh
test/controllers/StopControllerSpec.scala
test/controllers/actions/FakeServiceInfoAction.scala
test/forms/StopFormProviderSpec.scala
test/utils/FakeNavigator.scala
test/utils/NextPageSpec.scala
test/views/StopViewSpec.scala

* Stop corporation tax page added and functioning
* Fixed the welsh toggle to be in the right place
* Removed the hmrc branding from the header

BTA-350 | Finished the stop ct page

---

app/config/FrontendAppConfig.scala
app/controllers/SubpageController.scala
app/controllers/actions/AuthAction.scala
app/models/requests/AuthenticatedRequest.scala
app/views/subpage.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
conf/messages.en
migrations/applied_migrations/Subpage.sh
test/controllers/SubpageControllerSpec.scala
test/controllers/actions/DataRetrievalActionSpec.scala
test/controllers/actions/FakeAuthAction.scala
test/views/SubpageViewSpec.scala
test/views/ViewSpecBase.scala

* Subpage template created using scaffold
* Sidebar CT UTR added
* Two links in the sidebar added

BTA-350 | subpage template created with sidebar

---

app/config/FrontendAppConfig.scala
app/utils/PortalUrlBuilder.scala
app/views/subpage.scala.html
conf/application.conf
conf/logback.xml
conf/messages.cy
conf/messages.en
test/utils/PortalUrlBuilderSpec.scala
test/views/SubpageViewSpec.scala

Created Portal Url Builder to replace things like UTRs in links.

BTA-350 | More Option subpage links

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/config/FrontendAppConfig.scala
app/controllers/SubpageController.scala
app/views/components/heading.scala.html
app/views/partials/account_summary.scala.html
app/views/partials/generic_error.scala.html
app/views/subpage.scala.html
conf/application.conf
conf/messages.cy
conf/messages.en
test/controllers/SubpageControllerSpec.scala
test/views/IndexViewSpec.scala
test/views/StopViewSpec.scala
test/views/SubpageViewSpec.scala
test/views/ViewSpecBase.scala
test/views/behaviours/IntViewBehaviours.scala
test/views/behaviours/QuestionViewBehaviours.scala
test/views/behaviours/StringViewBehaviours.scala
test/views/behaviours/YesNoViewBehaviours.scala
test/views/partials/AccountSummaryViewSpec.scala
test/views/partials/GenericErrorViewSpec.scala

Subpage is almost complete.
* Has non partial content
* Partial non-dynamic content
* Negative cases
Remaining:
* styles
* partial content for balance

BTA-350 | Subpage Content

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/controllers/SubpageController.scala
app/views/components/heading.scala.html
app/views/partials/account_summary.scala.html
app/views/stop.scala.html
app/views/subpage.scala.html
conf/application.conf
conf/messages.cy
conf/messages.en
test/controllers/SubpageControllerSpec.scala

* In Credit
* In Debit
* Balanced
* null Balance
* changed 'you owe' from bold to panel-indent as per new styling used for self-assessment refactor

BTA-350 | Added balance information to subpage

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/assets/stylesheets/partials/_buttons.scss
app/assets/stylesheets/partials/_variables.scss
app/config/FrontendAppConfig.scala
app/controllers/actions/AuthAction.scala
app/views/govuk_wrapper.scala.html
app/views/partials/account_summary.scala.html
app/views/unauthorised.scala.html
conf/application.conf
conf/messages.cy
conf/messages.en
test/views/UnauthorisedViewSpec.scala
test/views/behaviours/ViewBehaviours.scala
test/views/partials/AccountSummaryViewSpec.scala

* Update design inline with prototype
* added signout button
* give unauthorised page for users without a CT enrolment

BTA-350 | Finish journey

---

app/config/FrontendAppConfig.scala
app/controllers/AccountSummaryHelper.scala
app/controllers/CheckYourAnswersController.scala
app/controllers/IndexController.scala
app/controllers/LanguageSwitchController.scala
app/controllers/PartialController.scala
app/controllers/SessionExpiredController.scala
app/controllers/StopController.scala
app/controllers/SubpageController.scala
app/controllers/UnauthorisedController.scala
app/controllers/actions/AuthAction.scala
app/controllers/actions/DataRequiredAction.scala
app/controllers/actions/DataRetrievalAction.scala
app/utils/PortalUrlBuilder.scala
app/views/partial.scala.html
app/views/subpage.scala.html
conf/app.routes
conf/messages.cy
conf/messages.en
migrations/applied_migrations/Partial.sh
test/controllers/AccountSummaryHelperSpec.scala
test/controllers/PartialControllerSpec.scala
test/controllers/SubpageControllerSpec.scala
test/controllers/actions/DataRetrievalActionSpec.scala
test/controllers/actions/FakeAuthAction.scala
test/utils/PortalUrlBuilderSpec.scala
test/views/PartialViewSpec.scala
test/views/SubpageViewSpec.scala

* Added heading
* Added UTR display
* Added account summary content
* Enforced the CtEnrolment to exist

BTA-350 | Implemented Partial Content

---

app/models/Stop.scala
app/utils/RadioOption.scala
app/views/components/submit_button.scala.html
conf/messages.cy
conf/messages.en
test/utils/RadioOptionSpec.scala

Fix for the ID being changed and breaking acceptance tests

BTA-453: Update id on field elements

---

conf/messages.cy
conf/messages.en

BTA-838: Side bar changes required to CT, VAT and SA for Help with Tax

BTA-838: Side bar changes required to CT, VAT and SA for Help with Tax

---

app/views/subpage.scala.html
test/views/SubpageViewSpec.scala

BTA-1445- Re-style top-of-page notifications in BTA homepage -MISSED SCENARIOS

BTA-1445: Re-style top-of-page notifications in BTA homepage -MISSED SCENARIOS

---

app/views/partials/card/payments/in_credit.scala.html
app/views/partials/card/payments/in_debit.scala.html
app/views/partials/card/payments/no_balance.scala.html
app/views/partials/card/payments/no_data.scala.html
test/views/partials/card/payments/InCreditViewSpec.scala
test/views/partials/card/payments/InDebitViewSpec.scala
test/views/partials/card/payments/NoBalanceViewSpec.scala
test/views/partials/card/payments/NoDataViewSpec.scala

BTA-1479 : CT - View statement link

BTA-1479 : CT - View statement link

---

conf/messages.cy

BTA-1280: Fix welsh translation in side menu link

BTA-1280: Fix welsh translation in side menu link

---

app/views/components/input_radio.scala.html
test/views/componants/InputRadioSpec.scala

BTA-1627 : Added align class to radio button

BTA-1627 : Added align class to radio button

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/views/components/heading.scala.html
app/views/components/input_radio.scala.html
app/views/stop.scala.html
test/views/componants/HeadingSpec.scala
test/views/componants/InputRadioSpec.scala

BTA-1628 : Fixed error pattern

BTA-1628 : Fixed error pattern

---

app/services/CtCardBuilderService.scala
app/views/partials/card/payments/in_credit.scala.html
app/views/partials/card/payments/in_debit.scala.html
app/views/partials/card/payments/no_balance.scala.html
app/views/partials/card/payments/no_data.scala.html
test/services/CtCardBuilderServiceSpec.scala
test/services/CtPartialBuilderSpec.scala
test/views/partials/card/payments/InCreditViewSpec.scala
test/views/partials/card/payments/InDebitViewSpec.scala
test/views/partials/card/payments/NoBalanceViewSpec.scala
test/views/partials/card/payments/NoDataViewSpec.scala

BTA-1750 : Change 'View your statement' position for CT and VAT

BTA-1750 : Change 'View your statement' position for CT and VAT

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/assets/stylesheets/partials/_focus.scss
app/assets/stylesheets/partials/_palette.scss

BTA-1852 : Added focus classes

BTA-1852 : Added focus classes

---

app/views/components/error_summary.scala.html
conf/messages.en
test/views/componants/ErrorSummarySpec.scala

BTA-1862: Added role to error summary

BTA-1862: Added role to error summary

---

app/views/govuk_wrapper.scala.html
conf/messages.cy
conf/messages.en

BTA-1871: Added region for language switch

BTA-1871: Added region for language switch

---

app/views/components/answer_section.scala.html
app/views/components/error_summary.scala.html
app/views/components/repeater_answer_section.scala.html
app/views/partials/card/payments/in_credit.scala.html
app/views/partials/card/payments/in_debit.scala.html
app/views/partials/card/payments/no_balance.scala.html
app/views/partials/card/payments/no_data.scala.html

BTA-1910 : Removed role text for paragraphs

BTA-1910 : Removed role text for paragraphs

---

app/assets/javascripts/error_summary_focus.js
app/views/components/error_summary.scala.html
app/views/govuk_wrapper.scala.html
test/views/componants/ErrorSummarySpec.scala

BTA-1863 : Added focus js when there is an error

BTA-1863 : Added focus js when there is an error

---

app/assets/stylesheets/corporationtaxfrontend-app.scss
app/views/components/input_radio.scala.html
app/views/components/input_text.scala.html
app/views/components/input_textarea.scala.html
app/views/components/input_yes_no.scala.html
app/views/main_template.scala.html
conf/messages.cy
conf/messages.en
test/views/components/InputRadioSpec.scala

BTA-1860: Added aria-described by for radio button

BTA-1860: Added aria-described by for radio button

---

app/views/main_template.scala.html
app/views/stop.scala.html
conf/messages.cy
conf/messages.en
test/views/StopViewSpec.scala

BTA-1621 : Added error in title if there is an form error

BTA-1621 : Added error in title if there is an form error

---

app/views/subpage.scala.html
conf/messages.cy
conf/messages.en
test/views/SubpageViewSpec.scala

BTA-1913 : Added welsh message

BTA-1913 : Fixed unique navigation issue

---

app/views/main_template.scala.html
app/views/partials/account_summary.scala.html
test/views/ViewSpecBase.scala
test/views/partials/AccountSummaryViewSpec.scala

BTA-2116 : Added role button to link with class=button

BTA-2116 : Added role button to link with class=button
